language: node_js
node_js:
  - "0.12"

install:
  - "npm install --save-dev qunitjs"
  - "npm install --save-dev sass"
  - "npm i qunit"
  - "npm i jquery@1.11.1"

#before_script:
#  - "./watch.sh"

script:
  - "node js/testrunner.js"
